using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Techbuzzers_bank.Models
{
    public class Account
    {
        [Key]
        [StringLength(12)]
        [RegularExpression("^[A-Z0-9]{12}$", ErrorMessage = "Account ID must be a 12-characters")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Auto-generated by the database
        public string Id { get; set; }
        

        [ForeignKey(nameof(UserDetails))]
        public string UserId { get; set; }

        [Required(ErrorMessage = "Balance is required")]
        [Range(0, double.MaxValue, ErrorMessage = "Balance must be a non-negative number")]
        public float Balance { get; set; }

        public List<Transactions> Transactions { get; set; } = new List<Transactions>();

        public List<Loans> Loans { get; set; } = new List<Loans>();
    }
}
