using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Security.Principal;
using System.Text.Json.Serialization;
using System.Transactions;

namespace Techbuzzers_bank.Models
{
    public class UserDetails
    {
        [Key]
        [StringLength(12)]
        [RegularExpression("^[A-Z0-9]{12}$", ErrorMessage = "User ID must be a 12-characters")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)] // Auto-generated by the database
        public string Id { get; set; }

        [Required(ErrorMessage = "First name is required")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last name is required")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Phone number is required")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Invalid phone number")]
        public long PhoneNumber { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [EmailAddress(ErrorMessage = "Invalid email address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Age is required")]
        [Range(12, 150, ErrorMessage = "Age must be between 12 and 150")]
        public int Age { get; set; }

        [Required(ErrorMessage = "Date of Birth is required")]
        [DataType(DataType.Date)]
        public DateTime Dob { get; set; }

        [Required(ErrorMessage = "Address is required")]
        public string Address { get; set; }

        

        [ForeignKey(nameof(Account))]
        public Account account { get; set; }

        [Required(ErrorMessage = "PIN is required")]
        [Range(1000, 9999, ErrorMessage = "PIN must be a 4-digit number")]
        public int Pin { get; set; }
    }
}
